DROP SCHEMA IF EXISTS FinalProject;
CREATE SCHEMA IF NOT EXISTS FinalProject;
USE FinalProject;

CREATE TABLE IF NOT EXISTS User (
ID INTEGER PRIMARY KEY AUTO_INCREMENT UNIQUE NOT NULL,
Name VARCHAR(255)  NOT NULL,
Surname VARCHAR(255)  NOT NULL,
Email VARCHAR(255) UNIQUE NOT NULL,
Password VARCHAR(255) NOT NULL,
Username VARCHAR(255) UNIQUE NOT NULL,
Organizer BOOLEAN,
Entity VARCHAR(255) NULL 
);

CREATE TABLE IF NOT EXISTS Event (
ID INTEGER PRIMARY KEY AUTO_INCREMENT UNIQUE NOT NULL,
Title VARCHAR(255) NOT NULL,
Description VARCHAR(255) NOT NULL,
Image VARCHAR(255) NULL,
Location VARCHAR(255) NOT NULL,
Duration VARCHAR(255) NOT NULL,
Dateandtime DATETIME NOT NULL
);


